Arrival to Triage Delay Median = 
VAR SelectedAcuityLevel =
    SELECTEDVALUE ( 'Acuity Selector'[Acuity Level] )
RETURN
    MEDIANX (
        FILTER (
            EDInformation,
            [Shift Filter] = 1
                && SWITCH (
                    TRUE (),
                    SelectedAcuityLevel = 0, EDInformation[Triage Level] = 0,
                    SelectedAcuityLevel = 1, EDInformation[Triage Level] IN { 1, 2, 3, 4, 5 },
                    SelectedAcuityLevel = 2, EDInformation[Triage Level] IN { 2, 3, 4, 5 },
                    SelectedAcuityLevel = 3, EDInformation[Triage Level] IN { 3, 4, 5 },
                    SelectedAcuityLevel = 4, EDInformation[Triage Level] IN { 4, 5 },
                    SelectedAcuityLevel = 5, EDInformation[Triage Level] = 5,
                    FALSE ()
                )
        ),
        DATEDIFF (
            EDInformation[Hour of Presentation],
            EDInformation[Hour of Triage],
            MINUTE
        ) / 60
    )