First Appointment = 
VAR SelectedAcuityLevel =
    SELECTEDVALUE ( 'Acuity Selector'[Acuity Level] )
RETURN
    CALCULATE (
        COUNTROWS ( EDInformation ),
        FILTER (
            EDInformation,
            [Shift Filter] = 1
                && EDInformation[Service Type Code] = "First"
                && SWITCH (
                    TRUE (),
                    SelectedAcuityLevel = 0, EDInformation[Triage Level] = 0,
                    SelectedAcuityLevel = 1, EDInformation[Triage Level] IN { 1, 2, 3, 4, 5 },
                    SelectedAcuityLevel = 2, EDInformation[Triage Level] IN { 2, 3, 4, 5 },
                    SelectedAcuityLevel = 3, EDInformation[Triage Level] IN { 3, 4, 5 },
                    SelectedAcuityLevel = 4, EDInformation[Triage Level] IN { 4, 5 },
                    SelectedAcuityLevel = 5, EDInformation[Triage Level] = 5,
                    FALSE ()
                )
        )
    )